### PR TITLE
set target and module into ES2020

### LINKED ISSUE #16: TypeError: Preview is not a function
Project created by `pnpm create vite my-vue-app --template vue-ts`
```json
"dependencies": {
  "vue": "^3.2.45"
},
"devDependencies": {
  "@vitejs/plugin-vue": "^4.0.0",
  "typescript": "^4.9.3",
  "vite": "^4.1.0",
  "vite-plugin-vue-component-preview": "^1.0.2",
  "vue-tsc": "^1.0.24"
}
```

In `vite.config.ts`,  `Preview()` got error `TypeError: Preview is not a function`, using `Preview.default()` works fine but got typescript error `Property 'default' does not exist on type '() => Plugin_2'.`

### PR DESCRIPTION
**Pull request by Take-Me1010**
may resolve #16

### CODE REVIEW

**Comment by johnsoncodehk** [comment]
Thanks!

**Comment by johnsoncodehk** [comment]
@Take-Me1010 does `"plugins": ["vite-plugin-vue-component-preview/tooling"]` still works to you with v1.1.0?

**Comment by Take-Me1010** [comment]
Actually I didn't pay attention to them and didn't test it.
Did you find any problems?

**Comment by johnsoncodehk** [comment]
> Actually I didn't pay attention to them and didn't test it. Did you find any problems?

Yes, but https://github.com/johnsoncodehk/vite-plugin-vue-component-preview/commit/4e419369c4a99982efc9550dff5b5b5651db640f should fixed it.

**Pull request merged**
